/******************************************************************************
 *                      Code generated with SymPy 1.13.2                      *
 *                                                                            *
 *              See http://www.sympy.org/ for more information.               *
 *                                                                            *
 *                      This file is part of 'autowrap'                       *
 ******************************************************************************/
#include "wrapped_code_0.h"
#include <math.h>

void autofunc(double roll, double pitch, double yaw, double roll_rh, double pitch_rh, double yaw_rh, double pitch_rk, double l1, double l2, double F, double *out_4648439795903864825) {

   out_4648439795903864825[0] = F*(-l1*(-(((-sin(yaw)*cos(pitch)*cos(yaw_rh) + sin(yaw_rh)*cos(pitch)*cos(yaw))*sin(roll_rh) + sin(pitch)*cos(roll_rh))*sin(pitch_rh) + (sin(yaw)*sin(yaw_rh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + (((-sin(yaw)*cos(pitch)*cos(yaw_rh) + sin(yaw_rh)*cos(pitch)*cos(yaw))*sin(roll_rh) + sin(pitch)*cos(roll_rh))*cos(pitch_rh) - (sin(yaw)*sin(yaw_rh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)) - (-l1 - l2)*(-(((-sin(yaw)*cos(pitch)*cos(yaw_rh) + sin(yaw_rh)*cos(pitch)*cos(yaw))*sin(roll_rh) + sin(pitch)*cos(roll_rh))*sin(pitch_rh) + (sin(yaw)*sin(yaw_rh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + (((-sin(yaw)*cos(pitch)*cos(yaw_rh) + sin(yaw_rh)*cos(pitch)*cos(yaw))*sin(roll_rh) + sin(pitch)*cos(roll_rh))*cos(pitch_rh) - (sin(yaw)*sin(yaw_rh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)))/l2;
   out_4648439795903864825[1] = F*(-l1*(-((((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_rh))*sin(roll_rh) - sin(roll)*cos(pitch)*cos(roll_rh))*sin(pitch_rh) + (-(-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + ((((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_rh))*sin(roll_rh) - sin(roll)*cos(pitch)*cos(roll_rh))*cos(pitch_rh) - (-(-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)) - (-l1 - l2)*(-((((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_rh))*sin(roll_rh) - sin(roll)*cos(pitch)*cos(roll_rh))*sin(pitch_rh) + (-(-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + ((((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_rh))*sin(roll_rh) - sin(roll)*cos(pitch)*cos(roll_rh))*cos(pitch_rh) - (-(-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_rh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)))/l2;
   out_4648439795903864825[2] = F*(-l1*(-((((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_rh))*sin(roll_rh) + cos(pitch)*cos(roll)*cos(roll_rh))*sin(pitch_rh) + (-(sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + ((((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_rh))*sin(roll_rh) + cos(pitch)*cos(roll)*cos(roll_rh))*cos(pitch_rh) - (-(sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)) - (-l1 - l2)*(-((((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_rh))*sin(roll_rh) + cos(pitch)*cos(roll)*cos(roll_rh))*sin(pitch_rh) + (-(sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_rh))*cos(pitch_rh))*sin(pitch_rk) + ((((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_rh))*sin(roll_rh) + cos(pitch)*cos(roll)*cos(roll_rh))*cos(pitch_rh) - (-(sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_rh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_rh))*sin(pitch_rh))*cos(pitch_rk)))/l2;
   out_4648439795903864825[3] = 0;

}
