import numpy as np
cimport numpy as np

cdef extern from 'wrapped_code_0.h':
    void autofunc(double roll, double pitch, double yaw, double roll_lh, double pitch_lh, double yaw_lh, double pitch_lk, double roll_rh, double pitch_rh, double yaw_rh, double pitch_rk, double dx, double dy, double dz, double droll, double dpitch, double dyaw, double droll_lh, double dpitch_lh, double dyaw_lh, double dpitch_lk, double droll_rh, double dpitch_rh, double dyaw_rh, double dpitch_rk, double ddx, double ddy, double ddz, double ddroll, double ddpitch, double ddyaw, double ddroll_lh, double ddpitch_lh, double ddyaw_lh, double ddpitch_lk, double ddroll_rh, double ddpitch_rh, double ddyaw_rh, double ddpitch_rk, double w, double l0, double l1, double l2, double g, double mb, double mt, double mc, double Ibx, double Iby, double Ibz, double Itx, double Ity, double Itz, double Icx, double Icy, double Icz, double *out_6517708235829091609)

def autofunc_c(double roll, double pitch, double yaw, double roll_lh, double pitch_lh, double yaw_lh, double pitch_lk, double roll_rh, double pitch_rh, double yaw_rh, double pitch_rk, double dx, double dy, double dz, double droll, double dpitch, double dyaw, double droll_lh, double dpitch_lh, double dyaw_lh, double dpitch_lk, double droll_rh, double dpitch_rh, double dyaw_rh, double dpitch_rk, double ddx, double ddy, double ddz, double ddroll, double ddpitch, double ddyaw, double ddroll_lh, double ddpitch_lh, double ddyaw_lh, double ddpitch_lk, double ddroll_rh, double ddpitch_rh, double ddyaw_rh, double ddpitch_rk, double w, double l0, double l1, double l2, double g, double mb, double mt, double mc, double Ibx, double Iby, double Ibz, double Itx, double Ity, double Itz, double Icx, double Icy, double Icz):

    cdef np.ndarray[np.double_t, ndim=2] out_6517708235829091609 = np.empty((14,1))
    autofunc(roll, pitch, yaw, roll_lh, pitch_lh, yaw_lh, pitch_lk, roll_rh, pitch_rh, yaw_rh, pitch_rk, dx, dy, dz, droll, dpitch, dyaw, droll_lh, dpitch_lh, dyaw_lh, dpitch_lk, droll_rh, dpitch_rh, dyaw_rh, dpitch_rk, ddx, ddy, ddz, ddroll, ddpitch, ddyaw, ddroll_lh, ddpitch_lh, ddyaw_lh, ddpitch_lk, ddroll_rh, ddpitch_rh, ddyaw_rh, ddpitch_rk, w, l0, l1, l2, g, mb, mt, mc, Ibx, Iby, Ibz, Itx, Ity, Itz, Icx, Icy, Icz, <double*> out_6517708235829091609.data)
    return out_6517708235829091609