/******************************************************************************
 *                      Code generated with SymPy 1.13.2                      *
 *                                                                            *
 *              See http://www.sympy.org/ for more information.               *
 *                                                                            *
 *                      This file is part of 'autowrap'                       *
 ******************************************************************************/
#include "wrapped_code_0.h"
#include <math.h>

void autofunc(double roll, double pitch, double yaw, double roll_lh, double pitch_lh, double yaw_lh, double pitch_lk, double l1, double l2, double F, double *out_2295845040945408997) {

   out_2295845040945408997[0] = F*(-l1*(-((-(-sin(yaw)*cos(pitch)*cos(yaw_lh) - sin(yaw_lh)*cos(pitch)*cos(yaw))*sin(roll_lh) + sin(pitch)*cos(roll_lh))*sin(pitch_lh) + (-sin(yaw)*sin(yaw_lh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-(-sin(yaw)*cos(pitch)*cos(yaw_lh) - sin(yaw_lh)*cos(pitch)*cos(yaw))*sin(roll_lh) + sin(pitch)*cos(roll_lh))*cos(pitch_lh) - (-sin(yaw)*sin(yaw_lh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)) - (-l1 - l2)*(-((-(-sin(yaw)*cos(pitch)*cos(yaw_lh) - sin(yaw_lh)*cos(pitch)*cos(yaw))*sin(roll_lh) + sin(pitch)*cos(roll_lh))*sin(pitch_lh) + (-sin(yaw)*sin(yaw_lh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-(-sin(yaw)*cos(pitch)*cos(yaw_lh) - sin(yaw_lh)*cos(pitch)*cos(yaw))*sin(roll_lh) + sin(pitch)*cos(roll_lh))*cos(pitch_lh) - (-sin(yaw)*sin(yaw_lh)*cos(pitch) + cos(pitch)*cos(yaw)*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)))/l2;
   out_2295845040945408997[1] = F*(-l1*(-((-((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_lh) - (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_lh))*sin(roll_lh) - sin(roll)*cos(pitch)*cos(roll_lh))*sin(pitch_lh) + ((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_lh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_lh) - (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_lh))*sin(roll_lh) - sin(roll)*cos(pitch)*cos(roll_lh))*cos(pitch_lh) - ((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_lh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)) - (-l1 - l2)*(-((-((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_lh) - (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_lh))*sin(roll_lh) - sin(roll)*cos(pitch)*cos(roll_lh))*sin(pitch_lh) + ((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_lh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*cos(yaw_lh) - (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*sin(yaw_lh))*sin(roll_lh) - sin(roll)*cos(pitch)*cos(roll_lh))*cos(pitch_lh) - ((-sin(pitch)*sin(roll)*sin(yaw) + cos(roll)*cos(yaw))*sin(yaw_lh) + (sin(pitch)*sin(roll)*cos(yaw) + sin(yaw)*cos(roll))*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)))/l2;
   out_2295845040945408997[2] = F*(-l1*(-((-((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_lh) - (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_lh))*sin(roll_lh) + cos(pitch)*cos(roll)*cos(roll_lh))*sin(pitch_lh) + ((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_lh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_lh) - (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_lh))*sin(roll_lh) + cos(pitch)*cos(roll)*cos(roll_lh))*cos(pitch_lh) - ((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_lh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)) - (-l1 - l2)*(-((-((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_lh) - (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_lh))*sin(roll_lh) + cos(pitch)*cos(roll)*cos(roll_lh))*sin(pitch_lh) + ((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_lh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_lh))*cos(pitch_lh))*sin(pitch_lk) + ((-((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*cos(yaw_lh) - (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*sin(yaw_lh))*sin(roll_lh) + cos(pitch)*cos(roll)*cos(roll_lh))*cos(pitch_lh) - ((sin(pitch)*sin(yaw)*cos(roll) + sin(roll)*cos(yaw))*sin(yaw_lh) + (-sin(pitch)*cos(roll)*cos(yaw) + sin(roll)*sin(yaw))*cos(yaw_lh))*sin(pitch_lh))*cos(pitch_lk)))/l2;

}
